### ISSUE TITLE
Update Clojure side to utilize latest from clojang library

### ISSUE THREAD

**Issue by oubiwann** [clojang/lfecljapp#21]
* [x] Remove all old Clojure code - #22
* [x] Create new Clojure server example - #23
* [x] Ensure the new Clojure example can be started with `lein` - #24

Part of release #20 (0.4.0)

**Comment by oubiwann** [comment]
Done.
