### ISSUE TITLE
Support running Clojure nodes from LFE

### ISSUE THREAD

**Issue by oubiwann** [clojang/lfecljapp#26]
This has previously been done in an ad hoc manner, and we need to make it easy for developers to start Clojure nodes from LFE using methodologies familiar to Clojure developers. We'll start with support for `lein` and the assumption of a `lein`-based Clojure project, but we can extend that to `boot` and raw `java` later. Maybe even `maven`.

Features required in Clojang to support this effort:

* [ ] Add new behaviour defining functions for working with JVM-based OTP nodes
* [ ] Add new behaviour implementation for managing `lein`-based nodes
* [ ] Add new behaviour implementation for managing nodes via `.jar` file

Part of release #20 (0.4.0)
