### ISSUE TITLE
Redo documentation

### ISSUE THREAD

**Issue by oubiwann** [clojang/lfecljapp#28]
Tasks:

* [ ] Update existing content in README - #
* [ ] Add documentation for working with nodes in the REPL - #
* [ ] Add documentation for starting JVM nodes from LFE - #
* [ ] Add documentation for managing nodes with a supervision tree - #

Part of release #20 (0.4.0)
