### ISSUE TITLE
Publish Blog Series on Clojang with lfecljapp as example

### ISSUE THREAD

**Issue by oubiwann** [clojang/lfecljapp#42]
Posts:

 * [ ] An introduction to Clojang - #
 * [ ] Writing a Clojure Server that Speaks Erlang - #
 * [ ] Talking to an LFE `gen_server` from Clojure - #
 * [ ] Starting JVM OTP Nodes from LFE - #
 * [ ] Running JVM Nodes in an LFE Supervision Tree - #

Part of release #20 (0.4.0)
